name: calculadora_financeira
description: "A new Flutter project."
publish_to: 'none'
version: 0.1.0

environment:
  sdk: ^3.5.4

dependencies:
  flutter:
    sdk: flutter
  intl: ^0.19.0
  fl_chart: ^0.69.2
  flutter_multi_formatter: ^2.13.0
  font_awesome_flutter: ^10.8.0
  http: ^1.2.2
  sqflite: ^2.2.5
  path: ^1.8.3
  provider: ^6.1.2
  google_fonts: ^5.0.0
  url_launcher: ^6.1.10
  shared_preferences: ^2.4.0
  flutter_email_sender: ^6.0.3
  mailer: ^6.4.1
  flutter_launcher_icons: ^0.14.3
  supabase_flutter: ^2.8.3
  image_picker: ^1.0.7
  path_provider: ^2.1.3
  
dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^4.0.0

flutter:
  uses-material-design: true
  assets:
    - lib/imagens/inicio.png
    - assets/tickers.json
    - assets/logo.png
    - assets/icon.png
  
flutter_launcher_icons:
  android: true
  ios: true
  image_path: "assets/icon.png" 
